apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-goapp-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "ms-goapp-cert"
spec:
  rules:
    - host: goapp.34.54.158.3.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-goapp-svc
                port:
                  number: 80
  tls:
    - hosts:
        - goapp.34.54.158.3.nip.io
      secretName: unused-secret
