apiVersion: v1
kind: Service
metadata:
  name: ms-goapp-svc
  labels:
    app: ms-goapp
spec:
  type: ClusterIP
  selector:
    app: ms-goapp
  ports:
    - name: http
      port: 80
      targetPort: 5700